services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./devops-backend
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
    expose:
      - "3000"

  frontend:
    build: ./devops-front
    container_name: frontend
    depends_on:
      - backend
    expose:
      - "80"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
